version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/serverdev
    overwrite: yes
permissions:
  - object: /home/ubuntu/serverdev
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before-be-dev-deploy.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/after-bedeploy.sh
      timeout: 180
      runas: ubuntu
